config/routes.rb
Gmaps::Application.routes.draw do
  resources :cities

end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :gmaps, :latitude, :longitude, :name, :population, :state

  acts_as_gmappable
  def gmaps4rails_address
    "#{name}, #{state}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
    @json = @cities.to_gmaps4rails do |city, marker|
      marker.infowindow render_to_string(:partial => "/cities/infowindow", :locals => { :city => city})
      marker.title "#{city.name}"
      marker.json({ :population => city.population})
      marker.picture({:picture => "assets/sight-2.png",
                    :width => 32,
                    :height => 32})
    end
    
    #@json = @cities.to_gmaps4rails

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cities }
    end
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
    @city = City.find(params[:id])
    
    @office = City.new(:name => "1500 N. Patterson St. Valdosta", :state => "GA")

    @output = Gmaps4rails.destination({:from => "#{@office.name}, #{@office.state}", 
                                       :to => "#{@city.name}, #{@city.state}"})
    
    @distance = @output.first["distance"]["text"]
    # The following converts the distance from a string to a float
    # @distance = @output.first["distance"]["text"].to_f
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @city }
    end
  end

  # GET /cities/new
  # GET /cities/new.json
  def new
    @city = City.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @city }
    end
  end

  # GET /cities/1/edit
  def edit
    @city = City.find(params[:id])
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(params[:city])

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render json: @city, status: :created, location: @city }
      else
        format.html { render action: "new" }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cities/1
  # PUT /cities/1.json
  def update
    @city = City.find(params[:id])

    respond_to do |format|
      if @city.update_attributes(params[:city])
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city = City.find(params[:id])
    @city.destroy

    respond_to do |format|
      format.html { redirect_to cities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% @city.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :population %><br />
    <%= f.number_field :population %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/_infowindow.html.erb
<h2><%= city.name %></h2>
<h3>population: <%= city.population %></h3>

app/views/cities/edit.html.erb
<h1>Editing city</h1>

<%= render 'form' %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<h1>Listing cities</h1>

<table>
  <tr>
    <th>Name</th>
    <th>State</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Gmaps</th>
    <th>Population</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cities.each do |city| %>
  <tr>
    <td><%= city.name %></td>
    <td><%= city.state %></td>
    <td><%= city.latitude %></td>
    <td><%= city.longitude %></td>
    <td><%= city.gmaps %></td>
    <td><%= city.population %></td>
    <td><%= link_to 'Show', city %></td>
    <td><%= link_to 'Edit', edit_city_path(city) %></td>
    <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
<%= gmaps4rails(@json) %>
<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<h1>New city</h1>

<%= render 'form' %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @city.name %>
</p>

<p>
  <b>State:</b>
  <%= @city.state %>
</p>

<p>
  <b>Latitude:</b>
  <%= @city.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @city.longitude %>
</p>

<p>
  <b>Gmaps:</b>
  <%= @city.gmaps %>
</p>

<p>
  <b>Population:</b>
  <%= @city.population %>
</p>


<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

<%= gmaps({ "direction" => { "data" => { "from" => @office.name + ", " + @office.state, "to" => @city.name + ", " + @city.state } } })%>

<p>
  <b>Distance</b>
  <%= @distance %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gmaps</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= yield :scripts %>
</body>
</html>